### ISSUE TITLE
設定ファイルからのストレージ実装切り替え機能の追加

### ISSUE THREAD

**Issue by magu6767** [magu6767/dependency-reverse-test#2]
## 目的
設定ファイルを使用してストレージの実装を動的に切り替える機能を追加する。

## タスク
1. [ ] 設定ファイル（`config.yaml`または`config.json`）の作成
2. [ ] 設定ファイルローダーの実装
3. [ ] ストレージファクトリークラスの実装
4. [ ] 動的なストレージ切り替えのサンプルコード作成

## 設定ファイルの例
```yaml
storage:
  type: file  # or memory
  file:
    path: data/users.json
  memory:
    thread_safe: true
```

## 実装のポイント
- 設定ファイルの形式は拡張性を考慮
- エラーハンドリングの実装
- デフォルト値の設定
- 実行時の設定変更への対応

## 期待される結果
- アプリケーションの再コンパイルなしでストレージを切り替え可能
- 環境ごとに異なる設定が可能
- 設定変更時のエラーメッセージが明確
